### PR TITLE
fix(caa upload): improve error message on invalid file types

### LINKED ISSUE #238: Improve error message on unsupported file formats
If we could, we should add the received MIME type in the error message (perhaps extract it from the fetch response header). We should also raise a specific error if we get text or HTML instead of images, since the user may have accidentally pasted the wrong link.

### PR DESCRIPTION
**Pull request by ROpdebee**
* Include actual MIME type returned by server in error message.
* Provide specific error message when content type is textual, as this may mean that the user is trying to use an unsupported provider.

Closes #238

### CODE REVIEW

File: src/mb_enhanced_cover_art_uploads/fetch.ts [hunk 1]
```diff
@@ -207,7 +207,12 @@ export class ImageFetcher {
                 } else if (uint32view[0] === 0x46445025) {
                     resolve('application/pdf');
                 } else {
-                    reject(new Error(`${fileName} has an unsupported file type`));
+                    const actualMimeType = resp.responseHeaders.match(/content-type:\s*([^;\s]+)/i)?.[1];
+                    if (actualMimeType?.startsWith('text/')) {
+                        reject(new Error(`Expected ${fileName} to be an image, but received text. Perhaps this provider is not supported yet?`));
```
Comment (kellnerd) [inline src/mb_enhanced_cover_art_uploads/fetch.ts:212]: Maybe we should not use the filename here since it is most likely not a filename in that case?
Since the default filename is `image` that often leads to messages like `Failed to grab images: Expected image to be an image, but received text. Perhaps this provider is not supported yet?`. Probably it is already enough to put the "filename" into quotes.

**Review by kellnerd — APPROVED** [review]

**Review by kellnerd — APPROVED** [review]
Thanks, that's even better than the possible message changes I had in mind.
